fsm_node:
  ros__parameters:
    states:
      - gap_following_only
    initial_state: gap_following_only
    objects_topic: object_bboxes
    output_topic: control_selector
    trailing_topic: trailing
