fsm_node:
  ros__parameters:
    states:
      - pure_pursuit_trailing
      - pure_pursuit
      - pure_pursuit_overtaking
    initial_state: pure_pursuit
    objects_topic: object_centers
    output_topic: control_selector
    global_path_topic: global_path
    overtaking_path_topic: /overtaking_spline/path
    final_path_topic: pp_path
    trailing_topic: trailing
    odom_topic: /car_state/odom

    overtaking_allowed_file_path: "/home/jetson/Desktop/mechabyte/software/src/giu_f1t_system/f1tenth_stack/path/overtaing_regions/under_5_mod_overtaking.csv"
    overtaking_path_timeout: 0.5