mcl_particle_filter_node:
  ros__parameters:
    angle_step: 51
    min_particles: 500
    max_particles: 3000
    max_viz_particles: 50
    squash_factor: 2.2
    max_range: 20.0
    theta_discretization: 150
    range_method: "glt"
    rangelib_variant: 3
    fine_timing: false
    publish_odom: false
    viz: false

    z_hit: 0.85
    z_short: 0.10
    z_max: 0.025
    z_rand: 0.025
    sigma_hit: 0.1

    alpha_1: 0.5
    alpha_2: 0.015
    alpha_3: 1.0
    alpha_4: 0.1
    lam_thresh: 0.1
    min_trans_update: 0.01
    reverse_velocity_thresh: -0.05
    reverse_spread: 1.1

    kld_err: 0.05
    kld_z: 0.99
    kld_bin_size_xy: 0.5
    kld_bin_size_theta: 0.1745
    alpha_slow: 0.001
    alpha_fast: 0.1
    resample_interval: 1

    scan_topic: "/scan"
    odometry_topic: "/odom"
    static_map: "map_server/map"
