teleop_switcher:
  ros__parameters:
    joy_topic: "/joy"
    selector_topic: "/control_selector"

    controllers:
      - lqr
      - gap_following
      - pure_pursuit
      - teleop

    manual_button_index: 7