csv_path_pub:
  ros__parameters:
    path_topic: "/global_path" # "csv_pp_path"
    csv_path: "/home/george/roboracer_sim/roboracer_ws/src/trajectory_planning/path/lab_map.csv"
    speed_factor: 1.0
    inverse: true
